FirstMVCApp/Controllers/OrderController.cs
using System;
using FirstMVCApp.DAL.Entities;
using FirstMVCApp.Models;
using FirstMVCApp.Services;
using Microsoft.AspNetCore.Mvc;

namespace FirstMVCApp.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;

        public OrderController(IOrderService orderService)
        {
            if (orderService == null)
                throw new ArgumentNullException(nameof(orderService));

            _orderService = orderService;
        }

        //action
        [Route("Order/Search/{name?}/{sumFrom?}/{sumTo?}")]
        public IActionResult Index([FromRoute] OrderFilterModel model)
        {
            try
            {
                var models = _orderService.SearchOrders(model);

                return View(models);
            }
            catch (ArgumentOutOfRangeException ex)
            {
                ViewBag.BadRequestMessage = ex.Message;
                return View("BadRequest");
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
        }

        public IActionResult Create()
        {
            var model = _orderService.GetOrderCreateModel();

            return View(model);
        }

        public IActionResult CreateWithProduct(int productId)
        {
            var model = _orderService.GetOrderCreateModel(productId);

            return View(model);
        }

        [HttpPost]
        public IActionResult Create(OrderCreateModel model)
        {
            try
            {
                _orderService.CreateOrder(model);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
        }
    }
}

FirstMVCApp/Controllers/ProductController.cs
using System;
using FirstMVCApp.Models;
using FirstMVCApp.Services;
using Microsoft.AspNetCore.Mvc;

namespace FirstMVCApp.Controllers
{
    public class ProductController : Controller
    {
        // DI - dependency injection
        private readonly IProductService _productService;

        public ProductController(IProductService productService)
        {
            if(productService == null)
                throw new ArgumentNullException(nameof(productService));

            _productService = productService;
        }

        //action
        [Route("Search/{name?}/{categoryId?}/{brandId?}/{priceFrom?}/{priceTo?}")]
        public IActionResult Index([FromRoute]ProductFilterModel model)
        {
            try
            {
                var models = _productService.SearchProducts(model);

                return View(models);
            }
            catch (ArgumentOutOfRangeException ex)
            {
                ViewBag.BadRequestMessage = ex.Message;
                return View("BadRequest");
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
        }

        public IActionResult Create()
        {
            var model = _productService.GetProductCreateModel();

            return View(model);
        }

        [HttpPost]
        public IActionResult Create(ProductCreateModel model)
        {
            try
            {
                _productService.CreateProduct(model);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
        }

        // Category Brand Name Price

        [Route("ololo")]
        public string GetString()
        {
            return "OLOLO";
        }
    }
}

FirstMVCApp/Views/Product/Create.cshtml
@model ProductCreateModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="Model.CategoriesSelect"></select>
            </div>
            <div class="form-group">
                <label asp-for="BrandId" class="control-label"></label>
                <select asp-for="BrandId" class="form-control" asp-items="Model.BrandsSelect">
                    <option></option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FirstMVCApp/Views/Product/Index.cshtml
@model List<ProductModel>
@{
    ViewData["Title"] = "Products";
}

<h1>Products</h1>
<hr/>
<a asp-controller="Product" class="btn-primary btn" asp-action="Create">Create</a>
<hr/>
<div class="row">
  @foreach (var product in Model)
      {
          <div class="col-sm-6">
              <div class="card">
                  <div class="card-header">
                      <p class="card-text">@product.CategoryName</p>
                  </div>
                  <div class="card-body">
                      <h3 class="card-title">@product.Name</h3>
                      <p class="card-text">@product.BrandName</p>
                      <h5>@product.Price</h5>
                      <a asp-controller="Order" class="btn-primary btn" asp-action="CreateWithProduct" asp-route-productId="@product.Id">Order</a>
                  </div>
              </div>
          </div>
      }
</div>
    