FirstMVCApp/Controllers/BrandController.cs
using System;
using FirstMVCApp.Models;
using FirstMVCApp.Services;
using Microsoft.AspNetCore.Mvc;

namespace FirstMVCApp.Controllers
{
    public class BrandController : Controller
    {
        // DI - dependency injection
        private readonly IBrandService _brandService;

        public BrandController(IBrandService brandService)
        {
            if(brandService == null)
                throw new ArgumentNullException(nameof(brandService));

            _brandService = brandService;
        }
        
        //action
        [Route("Brand/Search/{name?}")]
        public IActionResult Index([FromRoute]BrandFilterModel model)
        {
            try
            {
                var models = _brandService.SearchBrands(model);

                return View(models);
            }
            catch (ArgumentOutOfRangeException ex)
            {
                ViewBag.BadRequestMessage = ex.Message;
                return View("BadRequest");
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
        }

        public IActionResult Create()
        {
            var model = _brandService.GetBrandCreateModel();
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(BrandCreateModel model)
        {
            try
            {
                _brandService.CreateBrand(model);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
        }
    }
}

FirstMVCApp/Views/Brand/Create.cshtml
@model BrandCreateModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Brand</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FirstMVCApp/Views/Brand/Index.cshtml
@model List<BrandModel>
@{
    ViewData["Title"] = "Brands";
}

<h1>Brands</h1>
<hr/>
<a  class="btn-primary btn" asp-controller="Brand" asp-action="Create">Create</a>
<ol>
    @foreach (var brand in Model)
    {
        <li>@brand.Name</li>
    }
</ol>
    